version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - frontend_net
      - backend_net
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      PORT: 3001
      DB_HOST: db
      DB_USER: alumno
      DB_PASSWORD: alumno123
      DB_NAME: tienda_perritos
      DB_PORT: 3306
    networks:
      - backend_net
    depends_on:
      - db

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: tienda_perritos
      MYSQL_USER: alumno
      MYSQL_PASSWORD: alumno123
    networks:
      - backend_net
    volumes:
      - db_data:/var/lib/mysql

networks:
  frontend_net:
    driver: bridge

  backend_net:
    driver: bridge
    internal: true

volumes:
  db_data:
